def content(makeFns):
	w,wtd,e,ae=makeFns('w,wtd,e,ae')
	w("<h1>Что можно найти на сайте Комитета финансов</h1>\n")
	w("<p>Информация о бюджете находится в нескольких разделах "+ae("http://www.fincom.spb.ru/","сайта")+". Так получилось, что однотипная информация за разные периоды времени может быть в разных разделах.</p>\n")
	def aXlsx(link):
		return ae(link,'[xlsx]',title='электронная таблица xlsx')
	def aPdf(link):
		return ae(link,'[pdf]',title='pdf-документ')
	def aZipPdf(link):
		return ae(link,'[zip/pdf]',title='zip-архив с pdf-документом')
	def aHtmlDropdownNav(link):
		return ae(link,'[html]',title='несколько html-страниц с навигацией в виде выпадающего списка')
	w("<table>\n")
	w("<thead><tr>")
	w("<th>год</th>")
	w("<th title='губернатор на момент составления бюджета'>губернатор</th>")
	w("<th title='публикации «Бюджет в кратком изложении» и «Бюджет для граждан» объёмом 60—80 страниц'>презентация</th>")
	w("<th title='исполнение по ведомственной структуре расходов'>исполнение</th>")
	w("</tr></thead>\n")
	w("<tbody id='2000'><tr>")
	wtd("2000")
	wtd("Яковлев")
	wtd(aZipPdf('http://www.fincom.spb.ru/files/cf/presentations/budg00_l.zip'))
	wtd()
	w("</tr></tbody>\n")
	w("<tbody id='2001'><tr>")
	wtd("2001")
	wtd("Яковлев")
	wtd(aZipPdf('http://www.fincom.spb.ru/files/cf/presentations/bl_01.zip'))
	wtd()
	w("</tr></tbody>\n")
	w("<tbody id='2002'><tr>")
	wtd("2002")
	wtd("Яковлев")
	wtd()
	wtd()
	w("</tr></tbody>\n")
	w("<tbody id='2003'><tr>")
	wtd("2003")
	wtd("Яковлев")
	wtd(aZipPdf('http://www.fincom.spb.ru/files/cf/presentations/bl-03.zip'))
	wtd()
	w("</tr></tbody>\n")
	w("<tbody id='2004'><tr>")
	wtd("2004")
	wtd("Матвиенко")
	wtd(aZipPdf('http://www.fincom.spb.ru/files/cf/presentations/bl_04.zip'))
	wtd()
	w("</tr></tbody>\n")
	w("<tbody id='2005'><tr>")
	wtd("2005")
	wtd("Матвиенко")
	wtd(aZipPdf('http://www.fincom.spb.ru/files/cf/presentations/bl_05.zip')+' '+aHtmlDropdownNav('http://www.fincom.spb.ru/files/cf/presentations_html/Budjet_2005_short/bd2005.html'))
	wtd()
	w("</tr></tbody>\n")
	w("<tbody id='2006'><tr>")
	wtd("2006")
	wtd("Матвиенко")
	wtd(aPdf('http://www.fincom.spb.ru/files/cf/presentations_html/Budget_2006_short/budjet_2006_rus.pdf')+' '+aHtmlDropdownNav('http://www.fincom.spb.ru/files/cf/presentations_html/Budget_2006_short/bd2006.html'))
	wtd()
	w("</tr></tbody>\n")
	w("<tbody id='2007'><tr>")
	wtd("2007")
	wtd("Матвиенко")
	wtd(aPdf('http://www.fincom.spb.ru/files/cf/presentations_html/Budget_2007_short/budget_2007_rus.pdf')+' '+aHtmlDropdownNav('http://www.fincom.spb.ru/files/cf/presentations_html/Budget_2007_short/bd2007.html'))
	wtd(aZipPdf('http://www.fincom.spb.ru/files/cf/npd/budget/2007/ispolnenie/pril4.zip'))
	w("</tr></tbody>\n")
	w("<tbody id='2008'><tr>")
	wtd("2008")
	wtd("Матвиенко")
	wtd(aPdf('http://www.fincom.spb.ru/files/cf/presentations_html/Budget_2008_short/budget_2008_rus.pdf')+' '+aHtmlDropdownNav('http://www.fincom.spb.ru/files/cf/presentations_html/Budget_2008_short/bd2008.html'))
	wtd(aZipPdf('http://www.fincom.spb.ru/files/cf/npd/budget/2008/ispolnenie/isp08_pril4.zip'))
	w("</tr></tbody>\n")
	w("<tbody id='2009'><tr>")
	wtd("2009")
	wtd("Матвиенко")
	wtd()
	wtd(aPdf('http://www.fincom.spb.ru/files/cf/npd/budget/2009/ispolnenie/isp2009_pril4.pdf'))
	w("</tr></tbody>\n")
	w("<tbody id='2010'><tr>")
	wtd("2010")
	wtd("Матвиенко")
	wtd()
	wtd(aZipPdf('http://www.fincom.spb.ru/files/cf/npd/budget/2010/ispolnenie/isp2010-pril4.zip'))
	w("</tr></tbody>\n")
	w("<tbody id='2011'><tr>")
	wtd("2011")
	wtd("Матвиенко")
	wtd()
	wtd(aZipPdf('http://www.fincom.spb.ru/files/cf/npd/budget/2011/ispolnenie/isp2011-pr4.zip'))
	w("</tr></tbody>\n")
	w("<tbody id='2012'><tr>")
	wtd("2012")
	wtd("Полтавченко")
	wtd()
	wtd()
	w("</tr></tbody>\n")
	w("<tbody id='2013'><tr>")
	wtd("2013")
	wtd("Полтавченко")
	wtd(aPdf('http://www.fincom.spb.ru/files/cf/npd/budget/2013/full/BudgetForPeople.pdf'))
	wtd(aXlsx('http://www.fincom.spb.ru/files/cf/npd/budget/2013/ispolnenie/xls/isp2013-pr4.xlsx'))
	w("</tr></tbody>\n")
	w("<tbody id='2014'><tr>")
	wtd("2014")
	wtd("Полтавченко")
	wtd(aPdf('http://www.fincom.spb.ru/files/cf/npd/budget/2014/full/xls_doc/BudgetForPeople14-2.pdf'))
	wtd()
	w("</tr></tbody>\n")
	w("</table>\n")
